#!/usr/bin/env crystal
# This file is generated by "./tools/generate_proto.cr"

require "json"
require "file"

module ProtoGenerator
  VERSION = "v1.3"

  # Represents a CDP domain (like Target, Page, etc.)
  class Domain
    getter name : String
    getter experimental : Bool
    getter description : String
    getter definitions : Array(Definition)

    def initialize(@name : String, @experimental : Bool, @description : String)
      @definitions = [] of Definition
    end
  end

  # Represents a definition (type, command, event)
  abstract class Definition
    getter domain : Domain
    getter name : String
    getter origin_name : String
    getter description : String
    getter experimental : Bool
    getter deprecated : Bool

    def initialize(@domain : Domain, @name : String, @origin_name : String,
                   @description : String, @experimental : Bool, @deprecated : Bool)
    end

    abstract def generate_code : String
  end

  # Struct definition
  class StructDefinition < Definition
    getter properties : Array(Property)
    getter is_command : Bool
    getter has_return : Bool

    def initialize(domain, name, origin_name, description, experimental, deprecated,
                   @properties : Array(Property), @is_command : Bool, @has_return : Bool)
      super(domain, name, origin_name, description, experimental, deprecated)
    end

    def generate_code : String
      # TODO: generate struct with JSON::Serializable
      ""
    end
  end

  # Property of a struct
  class Property
    getter name : String
    getter type : String
    getter description : String
    getter optional : Bool
    getter experimental : Bool
    getter deprecated : Bool

    def initialize(@name : String, @type : String, @description : String,
                   @optional : Bool, @experimental : Bool, @deprecated : Bool)
    end
  end

  # Main generator
  class Generator
    @schema : JSON::Any

    def initialize(schema_path : String)
      content = File.read(schema_path)
      @schema = JSON.parse(content)
    end

    def run
      puts "Generating protocol bindings for CDP version #{@schema["version"]?}"

      # Parse domains
      domains = parse_domains

      # Generate files
      generate_domain_files(domains)
      generate_definitions_file(domains)

      puts "Done."
    end

    private def parse_domains : Array(Domain)
      domains = [] of Domain

      @schema["domains"].as_a.each do |domain_json|
        name = domain_json["domain"].as_s
        experimental = domain_json["experimental"]?.try(&.as_bool) || false
        description = domain_json["description"]?.try(&.as_s) || ""

        domain = Domain.new(name, experimental, description)

        # Parse types, commands, events
        # TODO: implement parsing logic

        domains << domain
      end

      domains
    end

    private def generate_domain_files(domains : Array(Domain))
      # Create lib/proto directory
      dir = "src/rod/lib/proto"
      Dir.mkdir_p(dir)

      # Clean up old generated files (except a_*.cr)
      Dir.glob("#{dir}/*.cr").each do |file|
        unless File.basename(file).starts_with?("a_")
          File.delete(file)
        end
      end

      # Generate each domain file
      domains.each do |_|
        # TODO: generate domain code
      end
    end

    private def generate_definitions_file(domains : Array(Domain))
      # TODO: generate definitions.cr with version and type map
    end
  end
end

# Main entry point
if ARGV.size != 1
  puts "Usage: crystal run tools/generate_proto.cr -- <schema.json>"
  puts "  schema.json: Path to CDP protocol JSON schema"
  exit 1
end

schema_path = ARGV[0]
generator = ProtoGenerator::Generator.new(schema_path)
generator.run
